# Generated by Django 3.0.7 on 2020-06-14 11:38

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('imgPath', models.ImageField(upload_to='')),
                ('duration', models.IntegerField()),
                ('genre', jsonfield.fields.JSONField()),
                ('language', models.CharField(max_length=30)),
                ('mpaaRating', jsonfield.fields.JSONField()),
                ('userRating', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
